---
- hosts: 172.31.10.225
  become: yes
  tasks:
  - name: i want to executeeeeee  direct linux command
    command: hostname -f
    register: myfirsttaskresult
    
  - name: i want to display first task result
    debug: "{{myfirsttaskresult}}"