---
- hosts: 172.31.10.225
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install websever server 
    apt:
      name: apache2
      state: present
  - name: copy static file into node side
    copy:
      src: mystaticfile
      dest: /home/ubuntu/mystaticfile

