---
- hosts: 172.31.10.225
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install websever server 
    apt:
      name: apache2
      state: present
  - name: copy static file into node side
    copy:
      src: mystaticfile
      dest: /home/ubuntu/mystaticfile

  - name:  download internet file
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes

  - name: copy index file into node side
    template:
       src: myindex.j2
       dest: /var/www/html/index.html
    notify: restartwebserver

  handlers: 
  - name: restartwebserver
    service:
       name: apache2
       state: restarted